In [0]:
import pandas as pd
 
# intialise data of lists.
data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}
 
# Create DataFrame
df = pd.DataFrame(data)
 
# Print the output.
print(df)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18


In [0]:
import pandas as pd
import numpy as np


In [0]:
import matplotlib.pyplot as  plt

In [0]:
%matplotlib inline

In [0]:
df=pd.read_csv("/content/Data.csv")

In [6]:
df


Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

**Count number of elements in each column**

In [7]:
df.count()

Country      10
Age           9
Salary        9
Purchased    10
dtype: int64

**Value_Counts -- Count frequency of each content in a column**

In [8]:
df['Country'].value_counts()

France     4
Germany    3
Spain      3
Name: Country, dtype: int64

**Convert dataframe into array--All execpt last output column**

Get feature vectors into array

In [0]:
x=df.iloc[:,:-1].values

In [10]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [0]:
y=df.iloc[:,-1].values

In [12]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

**Replace missing data using mean on dataframe**

In [0]:
df['Age'].fillna((df['Age'].mean()), inplace=True)

In [14]:
df

Country        Age   Salary Purchased
0   France  44.000000  72000.0        No
1    Spain  27.000000  48000.0       Yes
2  Germany  30.000000  54000.0        No
3    Spain  38.000000  61000.0        No
4  Germany  40.000000      NaN       Yes
5   France  35.000000  58000.0       Yes
6    Spain  38.777778  52000.0        No
7   France  48.000000  79000.0       Yes
8  Germany  50.000000  83000.0        No
9   France  37.000000  67000.0       Yes

In [0]:
df=df.astype({"Age": int})

In [16]:
df

Country  Age   Salary Purchased
0   France   44  72000.0        No
1    Spain   27  48000.0       Yes
2  Germany   30  54000.0        No
3    Spain   38  61000.0        No
4  Germany   40      NaN       Yes
5   France   35  58000.0       Yes
6    Spain   38  52000.0        No
7   France   48  79000.0       Yes
8  Germany   50  83000.0        No
9   France   37  67000.0       Yes

In [17]:
df.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

**Fill Missing values with mean on array**

In [0]:
from sklearn.impute import SimpleImputer

In [0]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer=imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])

In [20]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

**LabelEncoder,  Convert Text to numbers**

In [0]:
from sklearn.preprocessing import LabelEncoder

In [0]:
labelencoder_X=LabelEncoder()

In [0]:
x[:,0]=labelencoder_X.fit_transform(x[:,0])

In [24]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

It will consider these values as continuous numbers..Though they are not.
They are categorical values..We need to think sometghing about them.
Spain greater than germany..Doesn't make any sense

**So use Dummy Encoding.Use One Hot encoding.**

In [0]:
from sklearn.preprocessing import OneHotEncoder

**One Hot encoder has got some issues So Use keras insttead of OneHotEncoder
**

In [33]:
from keras.utils import to_categorical


Using TensorFlow backend.


In [0]:
encoded = to_categorical(x[:,0])



In [44]:
encoded

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)

**Remove redundancy**

In [0]:
c=encoded[:,[1,2]]

In [43]:
c

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.]], dtype=float32)

In [0]:
b=np.append(c,x, axis=1)


In [39]:
b

array([[0.0, 0.0, 0, 44.0, 72000.0],
       [0.0, 1.0, 2, 27.0, 48000.0],
       [1.0, 0.0, 1, 30.0, 54000.0],
       [0.0, 1.0, 2, 38.0, 61000.0],
       [1.0, 0.0, 1, 40.0, 63777.77777777778],
       [0.0, 0.0, 0, 35.0, 58000.0],
       [0.0, 1.0, 2, 38.77777777777778, 52000.0],
       [0.0, 0.0, 0, 48.0, 79000.0],
       [1.0, 0.0, 1, 50.0, 83000.0],
       [0.0, 0.0, 0, 37.0, 67000.0]], dtype=object)

**parameters of delete are array,column and axis**

In [0]:
b=np.delete(b,2,1)


In [0]:
x=b

In [42]:
x

array([[0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 37.0, 67000.0]], dtype=object)

No need to do the same for dependent output variable.As machine learning knows this is output column and we would be using categorical classification model.So we need not to use One hot encoder fot the output column.
Only Label enocoder will do all

In [0]:
labelencoder_Y=LabelEncoder()

In [0]:
y=labelencoder_Y.fit_transform(y)

In [48]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

**Split Datasets into Training and Test set**

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [72]:
X_train

array([[1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [73]:
X_test

array([[1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 50.0, 83000.0]], dtype=object)

In [74]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [75]:
y_test

array([0, 0])

**Feature scaling**

one value would be more dominating than the other,For eg. one in range of lakhs and other in 10s, if squared then result can be more dominated by single variable.
Do standardisation or normalisation
(x-mew)/sigma or (x-min)/(max-min)

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
sc_X=StandardScaler()

In [0]:
X_train=sc_X.fit_transform(X_train)


In [79]:
Do we need to fit our dummy/one hot variable

SyntaxError: ignored

In [80]:
X_train

array([[ 2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [-0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [-0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [-0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [-0.37796447, -0.77459667, -0.59788085, -0.48214934]])

In [0]:
X_test=sc_X.transform(X_test)

In [82]:
X_test

array([[ 2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [ 2.64575131, -0.77459667,  1.98496442,  2.13981082]])

1.Fit(): Method calculates the parameters μ and σ and saves them as internal objects.

2.Transform(): Method using these calculated parameters apply the transformation to a particular dataset.

3.Fit_transform(): joins the fit() and transform() method for transformation of dataset.